### ISSUE TITLE
Loading screen to be shown before the UI get started

### ISSUE THREAD

**Issue by tomasjanikds** [daattali/advanced-shiny#10]
Hi Dean,

I really like your work on Shiny (setting up VM, `shinyjs` etc.).

Would it be possible to trigger the 'Loading...' solution you came up with at the very beginning of the shiny app?
My use case is following:
At the very beginning of the `app.R` code I am connecting to the database and fetch the data into variable so I can use the data throughout the app and don't need to use database any more. This is all done before `ui` and `server` functions. The connection is the main time consumer of the app and was thinking about the 'Loading...' message for the user.
Your solution is working fine when I hide the *app-content* in `ui` function. However, connection to the database is made before. Is there any way how can the *loading-content* be shown before the connection to the database is made? You might maybe get my point when I list the starting part of my `app.R`:

```
# using dashboard package
library(shinydashboard)
library(plotly)
library(DT)
library(tidyverse)
library(RPostgreSQL)
library(shinyjs)

## Database connection
drv <- dbDriver('PostgreSQL')
con <- dbConnect(drv = drv, dbname = 'XX', user = 'XX', password = 'XX', port = XX, host ='XX')

# get the data and fetch
dash_data <- dbSendQuery(con, 'SELECT * from XX')
datadash <- fetch(dash_data, n = -1)

# disconnect
dbDisconnect(con)

appCSS <- "
#loading-content {
  position: absolute;
  background: #000000;
  opacity: 0.9;
  z-index: 100;
  left: 0;
  right: 0;
  height: 100%;
  text-align: center;
  color: #FFFFFF;
}
"

ui <- dashboardPage(
            
    dashboardHeader(title = "My Dashboard",
                    titleWidth = 250),

    dashboardSidebar(width = 150,
                     sidebarMenu(
                         menuItem("Dashboard", tabName = "dashboard", icon = icon("dashboard"))
                     )
    ),
    
    dashboardBody(
        tags$head(tags$style(HTML(".small-box {height: 50px}"))),
        
        useShinyjs(),
        inlineCSS(appCSS),
        
        # Loading message
         div(
             id = "loading-content",
             h2("Loading...")
         ),

         hidden(
             div(
                 id = "app-content",

        #the rest of the ui content ...

```

**Comment by daattali** [comment]
Unfortunately I don't think that's possible, because that code is being run before there is any user interface. There is nowhere to place a loading screen, the UI hasn't been created yet. You could ask the shiny team at RStudio, but I doubt there's a clean proper solution
