### ISSUE TITLE
withBusyIndicatorUI() creates div without data-for-btn argument

### ISSUE THREAD

**Issue by elcombato** [daattali/advanced-shiny#7]
Hi,

the function `withBusyIndicatorUI ` creates the [`div` without the attribute `data-for-btn` ](https://github.com/daattali/advanced-shiny/blob/master/busy-indicator/helpers.R#L13).
The attribute get assigned the variable `id`.
```R
`data-for-btn` = id,
```
If I change the assignment to any string instead of a variable, it works.
```R
`data-for-btn` = "anyButtonId",
```

**Comment by elcombato** [comment]
The problem in my code was in
```
id <- button[['attribs']][['id']]
```
because I used a `shinyFilesButton` from the package [`shinyFiles` ](https://github.com/thomasp85/shinyFiles).

**Comment by daattali** [comment]
Thanks for following up
