### ISSUE TITLE
Alternative for proxy-click JS-code

### ISSUE THREAD

**Issue by vnijs** [daattali/advanced-shiny#8]
In a navbarPage app I use the JS code below to create a key-board shortcut for a button that triggers a regression to run. Comments?

    $(document).keydown(function(event) {
      if ($("#reg_run").is(":visible") && (event.metaKey || event.ctrlKey) && event.keyCode == 13) {
        $("#reg_run").click();
      } 
    });

**Comment by daattali** [comment]
Correct me if I'm wrong, but this is a bit different. My proxy click solution was for attaching any button on the page to pressing "Enter" when you are inside a particular input. The code above manually attaches a specific button to pressing "Enter" anywhere on the page. You obviously know your javascript, and what you're using works better for your case. My proxy click solution is a more generic implementation

**Comment by vnijs** [comment]
Good point
